### ISSUE TITLE
Join forces/collaboration? 

### ISSUE THREAD

**Issue by mhartington** [chemzqm/tstool.nvim#1]
Hey there! I've noticed this plugin has some similar features/functionality to [nvim-typescript](https://github.com/mhartington/nvim-typescript). Would you be up for combining efforts/collaborating?

**Comment by chemzqm** [comment]
This plugin just some helper command for typescript development.
What valuable for me is it could be notified with terminal buffer even after neovim restart, but that feature only available for neovim 0.3.0 and would require some change to neovim's code, so the other user can't use that for now.

For the intelligence things, I'm working on https://github.com/neoclide/coc.nvim, it doesn't have too much feature for now, but it have support for completion item resolve, textEdits, automatic snippet (eg: function signature), additional text edits (eg: auto import for undefined function) and command support of completion item, which are possibly never available in completion plugin like deoplete.

![additional_textedits](https://user-images.githubusercontent.com/251450/41604277-674aade0-7411-11e8-9061-6b8a60267cbd.gif)
![snippet_choice](https://user-images.githubusercontent.com/251450/41604279-68774c14-7411-11e8-94c2-72f812150c0a.gif)

**Comment by chemzqm** [comment]
One thing we can do to improve the use experience is by using `balloonevalterm` which would allow user to get the documentation by mouse hover, instead of type command like `TSDoc` again and again.
But that would require to get this feature patched to neovim.
